### ISSUE TITLE
Secure Commit History and Update .gitignore

### ISSUE THREAD

**Issue by victor0villca** [zrock-dev/980#26]
**Description:** Remove sensitive data from commits, rewrite history, update .gitignore for security and cleanliness of repository.

**Comment by zrock-dev** [comment]
### Solution 

Rewrote the git history to erase the tracking of the files inside the dir: backend/.idea/

![image](https://github.com/zrock-dev/980/assets/64939916/6d41ae3a-358a-4743-a92d-424f6d12f300)

Note:
The rewriting was done using the tool: 
https://htmlpreview.github.io/?https%3A%2F%2Fgithub.com%2Fnewren%2Fgit-filter-repo%2Fblob%2Fdocs%2Fhtml%2Fgit-filter-repo.html=#EXAMPLES

**Comment by zrock-dev** [comment]
Related to: #20 

Solved by: https://tree.taiga.io/project/santiago_c_saavedra-980/us/100
